package render

import "strings"

// StyledText marks ANSI styling generated by the CLI after all dynamic content
// has been sanitized. It is the only Message argument that bypasses filtering.
type StyledText string

func Styled(s string) StyledText {
	return StyledText(s)
}

func SafeLine(s string) string {
	return terminalLine(s)
}

// terminalText neutralizes terminal controls in untrusted server text while
// preserving LF as document structure. Sanitization happens before the CLI adds
// its own ANSI styling, so legitimate rich output remains available.
func terminalText(s string) string {
	return strings.Map(func(r rune) rune {
		if r == '\n' {
			return r
		}
		if r < 0x20 || (r >= 0x7f && r <= 0x9f) {
			return '\uFFFD'
		}
		return r
	}, s)
}

// terminalLine additionally prevents untrusted text from creating table
// columns or extra output lines.
func terminalLine(s string) string {
	return strings.Map(func(r rune) rune {
		if r == '\n' {
			return ' '
		}
		return r
	}, terminalText(s))
}

// layoutLine is used only after server data has already passed terminalText.
// It preserves ANSI styling generated by the CLI itself while keeping table
// cells on one physical line.
func layoutLine(s string) string {
	return strings.NewReplacer("\n", " ", "\r", " ", "\t", " ").Replace(s)
}

func terminalLines(values []string) []string {
	clean := make([]string, len(values))
	for i, value := range values {
		clean[i] = terminalLine(value)
	}
	return clean
}

func terminalArg(value any) any {
	switch typed := value.(type) {
	case StyledText:
		return typed
	case string:
		return terminalLine(typed)
	case []string:
		return terminalLines(typed)
	case error:
		return terminalLine(typed.Error())
	default:
		return value
	}
}
